<?php

# Based on flyspray 0.9.9.6
# Copyright 2010, yetist <wuxiaotian@reflag-linux.com>

$modversion['name'] = _MI_FLYSPRAY_NAME;
$modversion['version'] = "0.96";
$modversion['description'] = _MI_FLYSPRAY_DESC;
$modversion['credits'] = "yetist <wuxiaotian@redflag-linux.com>";
$modversion['help'] = "no help yet";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/flyspray_slogo.png";
$modversion['dirname'] = "flyspray";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "flyspray_admin_requests";
$modversion['tables'][1] = "flyspray_assigned";
$modversion['tables'][2] = "flyspray_attachments";
$modversion['tables'][3] = "flyspray_cache";
$modversion['tables'][4] = "flyspray_comments";
$modversion['tables'][5] = "flyspray_dependencies";
$modversion['tables'][6] = "flyspray_groups";
$modversion['tables'][7] = "flyspray_history";
$modversion['tables'][8] = "flyspray_list_category";
$modversion['tables'][9] = "flyspray_list_os";
$modversion['tables'][10] = "flyspray_list_resolution";
$modversion['tables'][11] = "flyspray_list_status";
$modversion['tables'][12] = "flyspray_list_tasktype";
$modversion['tables'][13] = "flyspray_list_version";
$modversion['tables'][14] = "flyspray_notification_messages";
$modversion['tables'][15] = "flyspray_notification_recipients";
$modversion['tables'][16] = "flyspray_notifications";
$modversion['tables'][17] = "flyspray_prefs";
$modversion['tables'][18] = "flyspray_projects";
$modversion['tables'][19] = "flyspray_registrations";
$modversion['tables'][20] = "flyspray_related";
$modversion['tables'][21] = "flyspray_reminders";
$modversion['tables'][22] = "flyspray_searches";
$modversion['tables'][23] = "flyspray_tasks";
$modversion['tables'][24] = "flyspray_users";
$modversion['tables'][25] = "flyspray_users_in_groups";
$modversion['tables'][26] = "flyspray_votes";

// Admin things
$modversion['hasAdmin'] = 0;

#// Menu
#$modversion['hasMain'] = 1;
#$modversion['sub'][1]['name'] = _MI_FLYSPRAY_SMNAME1;
#$modversion['sub'][1]['url'] = "view_all_bug_page.php";
#$modversion['sub'][2]['name'] = _MI_FLYSPRAY_SMNAME2;
#$modversion['sub'][2]['url'] = "bug_report_page.php";

#// Search
#$modversion['hasSearch'] = 1;
#$modversion['search']['file'] = "include/search.inc.php";
#$modversion['search']['func'] = "mantis_search";

?>
